lib: [
  "F:/advent-2021/_esy/default/store/b/advent_2021-8956845b\\install/default/lib/day2/META"
  "F:/advent-2021/_esy/default/store/b/advent_2021-8956845b\\install/default/lib/day2/dune-package"
  "F:/advent-2021/_esy/default/store/b/advent_2021-8956845b\\install/default/lib/day2/opam"
]
bin: [
  "F:/advent-2021/_esy/default/store/b/advent_2021-8956845b\\install/default/bin/day1.exe"
  "F:/advent-2021/_esy/default/store/b/advent_2021-8956845b\\install/default/bin/day2.exe"
]
doc: [
  "F:/advent-2021/_esy/default/store/b/advent_2021-8956845b\\install/default/doc/day2/README.md"
]
